// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ProjetoSaudeVacina.Infra.Data.Context;
using System;

namespace ProjetoSaudeVacina.Infra.Data.Migrations
{
    [DbContext(typeof(ProjetoSaudeVacinaContext))]
    [Migration("20180711023045_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoSaudeVacina.Domain.Entities.PostoSaude", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCadastro");

                    b.Property<long>("Latitude");

                    b.Property<long>("Longitude");

                    b.Property<string>("Nome");

                    b.Property<long>("VacinaEstoqueId");

                    b.HasKey("Id");

                    b.HasIndex("VacinaEstoqueId");

                    b.ToTable("PostoSaude");
                });

            modelBuilder.Entity("ProjetoSaudeVacina.Domain.Entities.Vacina", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Vacina");
                });

            modelBuilder.Entity("ProjetoSaudeVacina.Domain.Entities.VacinaEstoque", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCadastro");

                    b.HasKey("Id");

                    b.ToTable("VacinaEstoque");
                });

            modelBuilder.Entity("ProjetoSaudeVacina.Domain.Entities.VacinaEstoqueItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCadastro");

                    b.Property<int>("Quantidade");

                    b.Property<long>("VacinaEstoqueId");

                    b.Property<long>("VacinaId");

                    b.HasKey("Id");

                    b.HasIndex("VacinaEstoqueId");

                    b.HasIndex("VacinaId");

                    b.ToTable("VacinaEstoqueItem");
                });

            modelBuilder.Entity("ProjetoSaudeVacina.Domain.Entities.PostoSaude", b =>
                {
                    b.HasOne("ProjetoSaudeVacina.Domain.Entities.VacinaEstoque", "VacinaEstoque")
                        .WithMany()
                        .HasForeignKey("VacinaEstoqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProjetoSaudeVacina.Domain.Entities.VacinaEstoqueItem", b =>
                {
                    b.HasOne("ProjetoSaudeVacina.Domain.Entities.VacinaEstoque", "VacinaEstoque")
                        .WithMany("VacinaEstoqueItens")
                        .HasForeignKey("VacinaEstoqueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjetoSaudeVacina.Domain.Entities.Vacina", "Vacina")
                        .WithMany()
                        .HasForeignKey("VacinaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
